export const PERMISSIONS = [
  "org.read",
  "org.update",
  "stores.read",
  "stores.manage",
  "users.read",
  "users.manage",
  "roles.manage",
  "leads.read",
  "leads.manage",
  "leads.assign",
  "leads.convert",
  "leads.import",
  "customers.read",
  "customers.manage",
  "products.read",
  "products.manage",
  "pricing.read",
  "pricing.manage",
  "inventory.read",
  "inventory.manage",
  "inventory.transfer",
  "orders.read",
  "orders.manage",
  "orders.confirm",
  "orders.cancel",
  "dispatch.read",
  "dispatch.manage",
  "sales.teams",
  "sales.targets",
  "sales.performance",
  "incentives.read",
  "incentives.manage",
  "incentives.approve",
  "reports.read",
  "audit.read",
  "notifications.read",
  "dashboard.read",
  "settings.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ALL_PERMISSIONS = [...PERMISSIONS];

export const ROLE_KEYS = {
  SUPER_ADMIN: "super_admin",
  STORE_MANAGER: "store_manager",
  SALES_MANAGER: "sales_manager",
  SALES_REP: "sales_rep",
  INVENTORY_MANAGER: "inventory_manager",
  DISPATCH_MANAGER: "dispatch_manager",
  CUSTOMER: "customer",
} as const;

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  super_admin: ALL_PERMISSIONS as Permission[],
  store_manager: [
    "org.read",
    "stores.read",
    "users.read",
    "users.manage",
    "leads.read",
    "leads.manage",
    "leads.assign",
    "leads.convert",
    "customers.read",
    "customers.manage",
    "products.read",
    "pricing.read",
    "inventory.read",
    "inventory.manage",
    "inventory.transfer",
    "orders.read",
    "orders.manage",
    "orders.confirm",
    "orders.cancel",
    "dispatch.read",
    "dispatch.manage",
    "sales.teams",
    "sales.targets",
    "sales.performance",
    "incentives.read",
    "reports.read",
    "notifications.read",
    "dashboard.read",
  ],
  sales_manager: [
    "org.read",
    "stores.read",
    "users.read",
    "leads.read",
    "leads.manage",
    "leads.assign",
    "leads.convert",
    "customers.read",
    "customers.manage",
    "products.read",
    "pricing.read",
    "pricing.manage",
    "orders.read",
    "orders.manage",
    "sales.teams",
    "sales.targets",
    "sales.performance",
    "incentives.read",
    "reports.read",
    "notifications.read",
    "dashboard.read",
  ],
  sales_rep: [
    "org.read",
    "stores.read",
    "leads.read",
    "leads.manage",
    "leads.convert",
    "leads.import",
    "customers.read",
    "customers.manage",
    "products.read",
    "pricing.read",
    "orders.read",
    "orders.manage",
    "sales.performance",
    "incentives.read",
    "notifications.read",
    "dashboard.read",
  ],
  inventory_manager: [
    "org.read",
    "stores.read",
    "products.read",
    "products.manage",
    "inventory.read",
    "inventory.manage",
    "inventory.transfer",
    "orders.read",
    "notifications.read",
    "dashboard.read",
    "reports.read",
  ],
  dispatch_manager: [
    "org.read",
    "stores.read",
    "customers.read",
    "products.read",
    "orders.read",
    "dispatch.read",
    "dispatch.manage",
    "inventory.read",
    "notifications.read",
    "dashboard.read",
  ],
  customer: [],
};
